### ISSUE TITLE
WebSocketBadStatusException: Handshake status 401

### ISSUE THREAD

**Issue by liorbp** [LPgenerator/mattermost_bot#13]
Seems like mattermost_bot is unable to maintain the websocket session.
After successfully connecting the bot to my team channel an exception is being raised:

```
[04/20/2016 15:31:10] Starting new HTTP connection (1): localhost
[04/20/2016 15:31:10] Starting new HTTP connection (1): localhost
[04/20/2016 15:31:10] connected to mattermost
[04/20/2016 15:31:10] loading plugin "plugins"
[04/20/2016 15:31:10] registered respond_to plugin "hello_reply" to "hello$"
[04/20/2016 15:31:10] registered listen_to plugin "hello_reply_formatting" to "hello_formatting$"
[04/20/2016 15:31:10] registered respond_to plugin "hello_reply_formatting" to "hello_formatting"
[04/20/2016 15:31:10] registered listen_to plugin "hello_send" to "hello$"
[04/20/2016 15:31:10] registered respond_to plugin "hello_decorators" to "hello_decorators"
[04/20/2016 15:31:10] registered listen_to plugin "hello_decorators" to "hello_decorators"
[04/20/2016 15:31:10] registered respond_to plugin "web_api_reply" to "hello_web_api"
[04/20/2016 15:31:10] registered listen_to plugin "hello_comment" to "hello_comment"
[04/20/2016 15:31:10] registered listen_to plugin "hello_react" to "hello_react"
[04/20/2016 15:31:10] registered respond_to plugin "busy_reply" to "busy"
[04/20/2016 15:31:10] registered respond_to plugin "ping_reply" to "ping"
[04/20/2016 15:31:10] keep active thread started
Traceback (most recent call last):
  File "cli.py", line 23, in <module>
    main()
  File "cli.py", line 18, in main
    b.run()
  File "/home/beepi/Desktop/mattermost_bot-master/mattermost_bot/bot.py", line 36, in run
    self._dispatcher.loop()
  File "/home/beepi/Desktop/mattermost_bot-master/mattermost_bot/dispatcher.py", line 103, in loop
    for self.event in self._client.messages(True, 'posted'):
  File "/home/beepi/Desktop/mattermost_bot-master/mattermost_bot/mattermost.py", line 135, in messages
    if not self.connect_websocket():
  File "/home/beepi/Desktop/mattermost_bot-master/mattermost_bot/mattermost.py", line 130, in connect_websocket
    "Cookie: MMTOKEN=%s" % self.api.token,
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 104, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 269, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_handshake.py", line 67, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_handshake.py", line 123, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 401
```

Using the internal IP instead of **localhost** didn't had any affect. Intercepting the network with Wireshark brings up this error from the server:

```
GET /api/v1/websocket?session_token_index=0&1 HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:8065
Origin: http://localhost:8065
Sec-WebSocket-Key: Q1cIz/zUgKKxIbQEhJmyxw==
Sec-WebSocket-Version: 13
Cookie: MMTOKEN=jewonarnkfy3jkfq8qk3apnj5h

HTTP/1.1 401 Unauthorized
Content-Type: application/json
Expires: 0
X-Ratelimit-Limit: 10
X-Ratelimit-Remaining: 9
X-Ratelimit-Reset: 1
X-Request-Id: sdb77przqjgep8u94ujm8tme5o
X-Version-Id: 2.1.0.1456234852
Date: Wed, 20 Apr 2016 12:25:19 GMT
Content-Length: 215

{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"UserRequired","request_id":"sdb77przqjgep8u94ujm8tme5o","status_code":401,"is_oauth":false}
```

I'm using mattermost_bot latest release on Linux Mint.
websocket-client-0.35.0 (I also tried to use 0.34.0)
requests 2.9.1
six 1.5.2

**Comment by liorbp** [comment]
I just realized that the cookie i'm getting from the mattermost server has an expire timestamp that is too short... no idea why:

```
POST /api/v1/users/login HTTP/1.1
Host: localhost:8065
Content-Length: 62
User-Agent: python-requests/2.9.1
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate

{"password": "mybot", "name": "myteam", "email": "mybot@nowhere.com"}

HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: MMAUTHTOKEN=ewbszg1pctn98doarczbty14ay; Path=/; **Expires=Fri, 20 May 2016 13:23:07 GMT**; Max-Age=2592000; HttpOnly
Token: ewbszg1pctn98doarczbty14ay
X-Ratelimit-Limit: 10
X-Ratelimit-Remaining: 9
X-Ratelimit-Reset: 1
X-Request-Id: 5j71ie18sj8ddb4sacqiwb34bh
X-Version-Id: 2.1.0.1456234852
Date: Wed, 20 Apr 2016 13:23:07 GMT
Content-Length: 551

{"id":"uon3kxzjpi8kxehqxeyskz598y","create_at":1461144243017,"update_at":1461146696043,"delete_at":0,"team_id":"mkydzb6quigduqfubxyra974my","username":"mybot","auth_service":"","email":"mybot@nowhere.com","nickname":"","first_name":"","last_name":"","roles":"admin","last_activity_at":1461158561863,"last_ping_at":1461158576077,"allow_marketing":true,"notify_props":{"all":"true","channel":"true","desktop":"all","desktop_sound":"true","email":"true","first_name":"false","mention_keys":"mybot,@mybot"},"last_password_update":1461144243017,"locale":"en"}
```

**Comment by benrobinson1993** [comment]
I had this problem...
quick fix update the following method with "MMAUTHTOKEN" rather than "MMTOKEN"

`
   def connect_websocket(self):
        host = self.api.url.replace('http', 'ws').replace('https', 'wss')
        url = host + '/websocket?session_token_index=0&1'
        print url
        print self.api.token
        self.websocket = websocket.create_connection(
            url, header=[
                "Cookie: MMAUTHTOKEN=%s" % self.api.token,
            ])
        return self.websocket.getstatus() == 101
`
Could be grossly misunderstanding as I have not dug through any more of the project but might help anyone who comes to go through this ticket properly.

The above update appears to work though.

**Comment by liorbp** [comment]
Damn you're right! I just compared this to how a regular request looks like from my web-browser.
I almost missed that :)

Thank you so much!

**Comment by gotlium** [comment]
which version of MM is used?

**Comment by benrobinson1993** [comment]
I cannot comment for @liorbp however
I installed via pip into a virtual environment and it did pull
mattermost-bot==1.0.13
a following
pip install -U mattermost-bot 

did pull the latest version though (without the problem) so does not seem to be reproducible. 

Can only say at some point this morning I managed to pull 1.0.13 rather than 1.0.14 without making the specification for a previous version.
