### ISSUE TITLE
NameError: name 'execfile' is not defined

### ISSUE THREAD

**Issue by Romerus** [LPgenerator/mattermost_bot#14]
Hi!
Iam using rhel7 and followd the instructions.
After Editing settings.py its time to get the bot running. 

```
[root@ mattermost_bot]# nano settings.py
[root@ mattermost_bot]# MATTERMOST_BOT_SETTINGS_MODULE=settings matterbot
Traceback (most recent call last):
  File "/usr/local/bin/matterbot", line 7, in <module>
    from mattermost_bot.cli import main
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/cli.py", line 5, in <module>
    from mattermost_bot import bot, settings
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/bot.py", line 15, in <module>
    from mattermost_bot import settings
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/settings.py", line 43, in <module>
    settings = importlib.import_module(settings_module)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/appl/bot/mattermost_bot/settings.py", line 44, in <module>
    execfile(settings.__file__.replace('.pyc', '.py'))
NameError: name 'execfile' is not defined
```
I use python 3.4.4 and i think execfile is not supported anymore with 3.x.x

I Installed via PIP
`[root@XXXXXXX bot]# sudo pip install mattermost_bot  --proxy="XXXXX@XXXXX":XXXXX@proxy.XXXX.XXX:XXXX --index-url=https://pypi.python.org/simple/ --trusted-host pypi.python.org --client-cert opt/appl/pypi.python.org.crt --target /opt/appl/bot`

after that i tested two ways, first i created 
mattermost_bot_settings.py

Content:
```
BOT_URL = 'http://<mm.example.com>/api/v1'  # with 'http://' and with '/api/v1' path
BOT_LOGIN = '<bot-email-address>'
BOT_PASSWORD = '<bot-password>'
BOT_TEAM = '<your-team>'
```
second way was to edit the settings.py with the correct credentials.
Both ways diddnt work for me.

**Comment by Romerus** [comment]
after a restart i have a other issue :(

```
[root@mattermost_bot]# MATTERMOST_BOT_SETTINGS_MODULE=settings matterbot
bash: matterbot: command not found...
```

**Comment by gotlium** [comment]
Hi, try to replace old code by following:

```python
if settings_module is not None:
    pwd = os.getcwd()
    if pwd not in sys.path:
        sys.path.insert(0, pwd)
    settings = importlib.import_module(settings_module)
    filename = settings.__file__.replace('.pyc', '.py')
    try:
        execfile(filename)
    except NameError:
        exec(open(filename).read())
```

**Comment by Romerus** [comment]
Diddnt help :(

```
for key in os.environ:
    if key[:15] == 'MATTERMOST_BOT_':
        globals()[key[11:]] = os.environ[key]

settings_module = os.environ.get('MATTERMOST_BOT_SETTINGS_MODULE')

if settings_module is not None:
    pwd = os.getcwd()
    if pwd not in sys.path:
        sys.path.insert(0, pwd)
    settings = importlib.import_module(settings_module)
    filename = settings.__file__.replace('.pyc', '.py')
    try:
        execfile(filename)
    except NameError:
        exec(open(filename).read())




try:
    from mattermost_bot_settings import *
except ImportError:
    try:
        from local_settings import *
    except ImportError:
        pass

if not BOT_URL.endswith('/api/v1'):
    BOT_URL = '%s%sapi/v1' % (BOT_URL, '' if BOT_URL.endswith('/') else '/')

```
**Error**

```
 MATTERMOST_BOT_SETTINGS_MODULE=settings matterbot

Traceback (most recent call last):
  File "<string>", line 46, in <module>
NameError: name 'execfile' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/matterbot", line 7, in <module>
    from mattermost_bot.cli import main
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/cli.py", line 5, in <module>
    from mattermost_bot import bot, settings
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/bot.py", line 15, in <module>
    from mattermost_bot import settings
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/settings.py", line 43, in <module>
    settings = importlib.import_module(settings_module)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/appl/bot/mattermost_bot/settings.py", line 48, in <module>
    exec(open(filename).read())
  File "<string>", line 48, in <module>

RuntimeError: maximum recursion depth exceeded during compilation
```

**Comment by Romerus** [comment]
Change for tests:

```
if settings_module is not None:
    pwd = os.getcwd()
    if pwd not in sys.path:
        sys.path.insert(0, pwd)
    settings = importlib.import_module(settings_module)
    filename = settings.__file__.replace('.pyc', '.py')
    try:
        exec(open(filename).read())
    except NameError:
        exec(open(filename).read())

```

Error:
```
MATTERMOST_BOT_SETTINGS_MODULE=settings matterbot
Traceback (most recent call last):
  File "/usr/local/bin/matterbot", line 7, in <module>
    from mattermost_bot.cli import main
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/cli.py", line 5, in <module>
    from mattermost_bot import bot, settings
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/bot.py", line 15, in <module>
    from mattermost_bot import settings
  File "/usr/local/lib/python3.4/site-packages/mattermost_bot/settings.py", line 43, in <module>
    settings = importlib.import_module(settings_module)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/appl/bot/mattermost_bot/settings.py", line 46, in <module>
    exec(open(filename).read())
  File "<string>", line 46, in <module>

 File "/usr/local/lib/python3.4/codecs.py", line 307, in __init__
    IncrementalDecoder.__init__(self, errors)
RuntimeError: maximum recursion depth exceeded

```

**Comment by Romerus** [comment]
Any Chance to get this fixed?

**Comment by gotlium** [comment]
Sorry, but I don't have a time at this moment. For quick fix, you can do patch by yourself.

**Comment by gotlium** [comment]
Today I test this case and all is working fine

    # python --version
    Python 3.4.4

    # MATTERMOST_BOT_SETTINGS_MODULE=mattermost_bot_settings /usr/local/opt/pyenv/versions/3.4.4/bin/matterbot 
    Hello, from settings!
    [05/29/2016 23:08:19] Starting new HTTP connection (1): xxx.xx
    ....

rename your directory from /opt/appl/bot/mattermost_bot/settings.py to /opt/appl/bot/`mm_bot`/settings.py. that should be fix RuntimeError.

**Comment by Romerus** [comment]
I use Mattermost 3.0, if i start pip i get only 1.0.14

**Comment by gotlium** [comment]
http://mattermost-bot.readthedocs.io/dev_install.html
