### ISSUE TITLE
Mattermost bot crashes a few seconds after start

### ISSUE THREAD

**Issue by Hanzei** [LPgenerator/mattermost_bot#28]
Hey guys,

I just installed the mattermost bot and tried to get it started. After configurating the `mattermost_bot_settings.py` I tried to start the bot with ` MATTERMOST_BOT_SETTINGS_MODULE=mattermost_bot_settings matterbot` but after a few seconds it crashed. This is the tracelog:
````
Traceback (most recent call last):
  File "/home/minerva/bin/matterbot", line 11, in <module>
    sys.exit(main())
  File "/home/minerva/.local/lib/python3.4/site-packages/mattermost_bot/cli.py", line 18, in main
    b.run()
  File "/home/minerva/.local/lib/python3.4/site-packages/mattermost_bot/bot.py", line 37, in run
    self._dispatcher.loop()
  File "/home/minerva/.local/lib/python3.4/site-packages/mattermost_bot/dispatcher.py", line 114, in loop
    for self.event in self._client.messages(True, 'posted'):
  File "/home/minerva/.local/lib/python3.4/site-packages/mattermost_bot/mattermost.py", line 189, in messages
    data = self.websocket.recv()
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_core.py", line 298, in recv
    opcode, data = self.recv_data()
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_core.py", line 315, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_core.py", line 328, in recv_data_frame
    frame = self.recv_frame()
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_core.py", line 360, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_core.py", line 429, in _recv
    return recv(self.sock, bufsize)
  File "/home/minerva/.local/lib/python3.4/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
````
Any ideas?

**Comment by gotlium** [comment]
Hi, Can you try it with python 2.7 and 3.5

**Comment by RossinesP** [comment]
Hi,
I've got the same kind of errors running python 2.7 and 3.4. They appear a few minutes after starting the bot, which prevents me from using it in production

**Comment by gotlium** [comment]
We are using this bot on production without problems. Possible you have a problems with internet connection. Install this bot on MM server, maybe it will be fix this problem.

**Comment by RossinesP** [comment]
Isn't there a way in the bot to re-establish a connection in case of failure ?
I will try installing it on the mattermost server. Is there a preferred python version to use ? Has the 3.5 version been tested more than the 2.7 one ?

**Comment by mcarlton00** [comment]
I have the restarting issue as well, but I'm mitigating it by using Supervisor.  The bot runs for roughly 1 minute and then dies, but I have supervisor set to auto restart it.

Also, it's running on a separate server than MM, just to chime in.

Same issues with Python 2.7 and 3.5.

**Comment by gotlium** [comment]
We are using Python 2.7.6, and don't have a problem with WS connection (bot installed on another host). 
Can you try test this code
```python
        # mattermost_bot/mattermost.py:188
        while True:
            try:
                data = self.websocket.recv()
            except:
                if not self.connect_websocket():
                    return
                continue
            if data:
```

**Comment by mcarlton00** [comment]
Adding in that bit of code seems to solve the problem.

We're running Mattermost 3.5

Python 2.7.11
```
$ env/bin/pip freeze
backports.ssl-match-hostname==3.5.0.1
dokuwiki==0.5.0
giphypop==0.2
mattermost-bot==1.0.19
requests==2.12.3
six==1.10.0
websocket-client==0.40.0
```

I removed the new code and it begins failing again.  Downgrading `requests` and `websocket-client` to match yours, as well as installing `pycrypto` still results in it erroring out.

**Comment by gotlium** [comment]
If you are using any proxy server, you must specify `Upgrade` and `Connection` headers and  `proxy_read_timeout` settings.
Example:

```nginx
server {
    server_name mattermost.example.com default;

    location / {
        client_max_body_size 50M;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Frame-Options SAMEORIGIN;
        proxy_read_timeout 86400;
        proxy_pass http://127.0.0.1:8065;
    }
}
```

**Comment by mcarlton00** [comment]
I don't directly have access to the server hosting mattermost, but the hoster says that's what we have.  Your new commit seems to have solved the problem for me, it hasn't crashed in the last 24 hours.

**Comment by Hanzei** [comment]
@gotlium Your code fixed my problem. Thanks!

**Comment by broglea** [comment]
I don't think this should be closed without a commit applying this error handling committed to GitHub.

**Comment by gig177** [comment]
@broglea What about [this one](https://github.com/LPgenerator/mattermost_bot/commit/92c401284d331c7713f959af20f1e13323dd5445)?

**Comment by broglea** [comment]
My apologies. The lack of referencing the commit in the issue confused me. I should have gone and looked at the commit history. Thanks for fixing this!
