### ISSUE TITLE
Team support ?

### ISSUE THREAD

**Issue by Madko** [LPgenerator/mattermost_bot#39]
Hi,
it seems mattermost_bot doesn't like when poeple speak to him from different team? Does mattermost_bot support this ?

Here is the traceback when sending msg to the bot from another team. The bot account is part of this other team.
```
Unhandled exception in thread started by <bound method WorkerPool.do_work of <mattermost_bot.utils.WorkerPool object at 0x7f82f4a35790>>
Traceback (most recent call last):
  File "/home/hubot/mattermost-bot/lib/python3.3/site-packages/mattermost_bot/utils.py", line 31, in do_work
    self.func(msg)
  File "/home/hubot/mattermost-bot/lib/python3.3/site-packages/mattermost_bot/dispatcher.py", line 64, in dispatch_msg
    if self.is_personal(msg):
  File "/home/hubot/mattermost-bot/lib/python3.3/site-packages/mattermost_bot/dispatcher.py", line 54, in is_personal
    channel_type = channel['channel']['type']
KeyError: 'channel'
```

Thanks for any help

**Comment by attzonko** [comment]
Hello, did you ever find a solution for this issue? I ran into the same problem. The only workaround I can come up with is to create a separate bot user for each team, and just run two separate instances of mattermost_bot. That seems ugly.

**Comment by attzonko** [comment]
The issue is the server returns error 500 with the message: There is no channel with channel_id=ojdoaz586381udmyxoaadhcs1w on team with team_id=n7or4d5km3r7mqez11hqcr7wiw

My guess is the bot code would need to be refactored to comprehend dealing with multiple teams.

**Comment by pidzvnese** [comment]
@gotlium Hello, did you ever find a solution for this issue? I ran into the same problem. The only workaround I can come up with is to create a separate bot user for each team, and just run two separate instances of mattermost_bot. That seems ugly.
