### ISSUE TITLE
405 Client Error: Method Not Allowed for url:

### ISSUE THREAD

**Issue by Anhellikal** [LPgenerator/mattermost_bot#58]
Hi After starting my bot with the simple:

from mattermost_bot.bot import Bot

`
if __name__ == "__main__":
    Bot().run()
`
I get the following:
`Traceback (most recent call last):
  File "C:/Users/user/IdeaProjects/mattermost_bot/mattermost_bot-master/mattermost_bot/main.py", line 5, in <module>
    Bot().run()
  File "C:\Software\Python\lib\site-packages\mattermost_bot\bot.py", line 27, in __init__
    settings.SSL_VERIFY
  File "C:\Software\Python\lib\site-packages\mattermost_bot\mattermost.py", line 154, in __init__
    self.login(team, email, password)
  File "C:\Software\Python\lib\site-packages\mattermost_bot\mattermost.py", line 158, in login
    self.user = self.api.login(team, email, password)
  File "C:\Software\Python\lib\site-packages\mattermost_bot\mattermost.py", line 51, in login
    p.raise_for_status()
  File "C:\Software\Python\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://*****/****/users/login`

**Comment by attzonko** [comment]
What version of Mattermost are you running?

If it is newer consider trying mmpy_bot we started with this bot and updated to support API4 and a few other fixes and enhancements. As far as I know this project is EOLed. 

https://github.com/attzonko/mmpy_bot
